# Generated by ChatGPT on 2026-01-27
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0005_alter_breedreference_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flock',
            name='weight_alert_high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='flock',
            name='weight_alert_low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='flock',
            name='initial_weight',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
