# Generated by Django 5.2.6 on 2026-02-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0006_add_weight_alert_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flock',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('SOLD', 'Vendido'), ('FINISHED', 'Terminado'), ('TRANSFERRED', 'Transferido')], default='ACTIVE', max_length=12),
        ),
    ]
