# Generated by Django 5.2.6 on 2026-02-12 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0007_alter_flock_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flock',
            name='current_quantity_female',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad actual hembras'),
        ),
        migrations.AddField(
            model_name='flock',
            name='current_quantity_male',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad actual machos'),
        ),
        migrations.AddField(
            model_name='flock',
            name='initial_quantity_female',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad inicial hembras'),
        ),
        migrations.AddField(
            model_name='flock',
            name='initial_quantity_male',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad inicial machos'),
        ),
        migrations.AddField(
            model_name='flock',
            name='initial_weight_female',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso inicial promedio hembras (g)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='flock',
            name='initial_weight_male',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso inicial promedio machos (g)', max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='DispatchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatch_date', models.DateField()),
                ('day_number', models.PositiveIntegerField(help_text='Día de edad al despacho')),
                ('manifest_number', models.CharField(help_text='Número de planilla', max_length=50)),
                ('shed_name', models.CharField(blank=True, help_text='Galpón', max_length=50)),
                ('males_count', models.PositiveIntegerField(default=0, help_text='Cantidad machos despachados')),
                ('females_count', models.PositiveIntegerField(default=0, help_text='Cantidad hembras despachadas')),
                ('total_birds', models.PositiveIntegerField(help_text='Total pollos despachados')),
                ('farm_avg_weight', models.DecimalField(decimal_places=2, help_text='Peso promedio granja (kg)', max_digits=8)),
                ('farm_total_kg', models.DecimalField(decimal_places=2, help_text='Kilos totales granja', max_digits=10)),
                ('plant_birds', models.PositiveIntegerField(blank=True, help_text='Pollos recibidos planta (descontando faltantes)', null=True)),
                ('plant_missing', models.PositiveIntegerField(default=0, help_text='Pollos faltantes en planta')),
                ('drowned', models.PositiveIntegerField(default=0, help_text='Ahogados en transporte')),
                ('plant_avg_weight', models.DecimalField(blank=True, decimal_places=4, help_text='Peso promedio planta (kg)', max_digits=8, null=True)),
                ('plant_total_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Kilos totales planta', max_digits=10, null=True)),
                ('plant_shrinkage_grams', models.DecimalField(blank=True, decimal_places=6, help_text='Merma planta (gramos por pollo)', max_digits=10, null=True)),
                ('sale_birds', models.PositiveIntegerField(blank=True, help_text='Pollos vendidos', null=True)),
                ('sale_discount_kg', models.DecimalField(decimal_places=2, default=0, help_text='Descuento en kilos', max_digits=10)),
                ('sale_total_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Kilos venta', max_digits=10, null=True)),
                ('sale_avg_weight', models.DecimalField(blank=True, decimal_places=6, help_text='Peso promedio venta (kg)', max_digits=8, null=True)),
                ('total_shrinkage_grams', models.DecimalField(blank=True, decimal_places=6, help_text='Merma total granja-venta (gramos por pollo)', max_digits=10, null=True)),
                ('observations', models.TextField(blank=True, help_text='Observaciones del despacho (ej: descuentos por comprador)')),
                ('client_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sync_status', models.CharField(default='SYNCED', max_length=20)),
                ('created_by_device', models.CharField(blank=True, max_length=100, null=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_records', to='flocks.flock')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dispatch_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('week_number', models.PositiveIntegerField(help_text='Número de semana desde llegada')),
                ('day_number', models.PositiveIntegerField(help_text='Día desde llegada (edad)')),
                ('mortality_male', models.PositiveIntegerField(default=0)),
                ('mortality_female', models.PositiveIntegerField(default=0)),
                ('process_output_male', models.PositiveIntegerField(default=0, help_text='Machos enviados a proceso')),
                ('process_output_female', models.PositiveIntegerField(default=0, help_text='Hembras enviadas a proceso')),
                ('balance_male', models.PositiveIntegerField(default=0, help_text='Saldo pollitos machos')),
                ('balance_female', models.PositiveIntegerField(default=0, help_text='Saldo pollitos hembras')),
                ('feed_consumed_kg_male', models.DecimalField(decimal_places=2, default=0, help_text='KG alimento consumido machos', max_digits=8)),
                ('feed_consumed_kg_female', models.DecimalField(decimal_places=2, default=0, help_text='KG alimento consumido hembras', max_digits=8)),
                ('feed_per_bird_gr_male', models.DecimalField(decimal_places=2, default=0, help_text='Consumo por pollo machos (gr)', max_digits=8)),
                ('feed_per_bird_gr_female', models.DecimalField(decimal_places=2, default=0, help_text='Consumo por pollo hembras (gr)', max_digits=8)),
                ('accumulated_feed_per_bird_gr_male', models.DecimalField(decimal_places=2, default=0, help_text='Consumo acumulado por pollo machos (gr)', max_digits=8)),
                ('accumulated_feed_per_bird_gr_female', models.DecimalField(decimal_places=2, default=0, help_text='Consumo acumulado por pollo hembras (gr)', max_digits=8)),
                ('weight_male', models.DecimalField(blank=True, decimal_places=2, help_text='Peso promedio machos (gr)', max_digits=8, null=True)),
                ('weight_female', models.DecimalField(blank=True, decimal_places=2, help_text='Peso promedio hembras (gr)', max_digits=8, null=True)),
                ('weekly_weight_gain_male', models.DecimalField(blank=True, decimal_places=2, help_text='Ganancia peso semanal machos (gr)', max_digits=8, null=True)),
                ('weekly_weight_gain_female', models.DecimalField(blank=True, decimal_places=2, help_text='Ganancia peso semanal hembras (gr)', max_digits=8, null=True)),
                ('daily_avg_weight_gain_male', models.DecimalField(blank=True, decimal_places=2, help_text='Ganancia peso promedio diario machos (gr)', max_digits=8, null=True)),
                ('daily_avg_weight_gain_female', models.DecimalField(blank=True, decimal_places=2, help_text='Ganancia peso promedio diario hembras (gr)', max_digits=8, null=True)),
                ('feed_conversion_male', models.DecimalField(blank=True, decimal_places=3, help_text='Conversión alimenticia machos', max_digits=6, null=True)),
                ('feed_conversion_female', models.DecimalField(blank=True, decimal_places=3, help_text='Conversión alimenticia hembras', max_digits=6, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True)),
                ('client_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sync_status', models.CharField(default='SYNCED', max_length=20)),
                ('created_by_device', models.CharField(blank=True, max_length=100, null=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='flocks.flock')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('flock', 'date')},
            },
        ),
    ]
