# Generated by Django 5.2.6 on 2026-02-13 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0008_flock_current_quantity_female_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SyncConflict',
            new_name='FlockSyncConflict',
        ),
        migrations.AlterModelTable(
            name='flocksyncconflict',
            table='flocks_syncconflict',
        ),
    ]
