# Generated by Django 5.2.6 on 2026-02-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0009_flocksyncconflict_delete_syncconflict_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flock',
            name='processing_stage',
            field=models.CharField(blank=True, choices=[('RECEPTION', 'Recepción y Espera'), ('HANGING', 'Colgado'), ('STUNNING', 'Aturdimiento y Sacrificio'), ('BLEEDING', 'Desangrado'), ('SCALDING', 'Escaldado y Desplumado'), ('EVISCERATION', 'Eviscerado'), ('POST_MORTEM', 'Inspección Post-Mortem'), ('CHILLING', 'Enfriamiento'), ('CLASSIFICATION', 'Clasificación y Empaque'), ('STORAGE', 'Almacenamiento y Distribución')], help_text='Sub-etapa de procesamiento (solo cuando production_stage=PROCESSING)', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='flock',
            name='production_stage',
            field=models.CharField(choices=[('BREEDER', 'Rebaño reproductor'), ('PULLET_FARM', 'Granja de pletinas'), ('BROODER', 'Casa criadora'), ('HATCHERY', 'Criadero'), ('GROW_OUT', 'Granja de engorde'), ('PROCESSING', 'Procesamiento'), ('DISTRIBUTION', 'Distribución')], default='GROW_OUT', help_text='Etapa del proceso de producción en la que se encuentra el lote', max_length=15),
        ),
    ]
