# Generated by Django 5.2.6 on 2026-03-01 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=200)),
                ('object_id', models.CharField(blank=True, max_length=200, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=500, null=True)),
                ('action', models.CharField(choices=[('created', 'Creado'), ('updated', 'Actualizado'), ('deleted', 'Eliminado')], max_length=20)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
