# Generated by Django 5.2.6 on 2026-03-01 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_add_veterinarians_to_farm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farm_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name__in': ['Administrador de Granja', 'Administrador Sistema']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_farms', to=settings.AUTH_USER_MODEL),
        ),
    ]
