# Generated by Django 5.2.6 on 2026-02-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0003_add_escalation_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('ACKNOWLEDGED', 'Atendida'), ('RESOLVED', 'Resuelta'), ('ESCALATED', 'Escalada')], default='PENDING', max_length=20),
        ),
    ]
