# Generated by Django 5.2.6 on 2026-03-02 00:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0006_notificationlog_read_at_is_deleted'),
        ('farms', '0005_alter_farm_farm_manager'),
        ('flocks', '0010_add_production_and_processing_stage'),
        ('inventory', '0004_foodbatch_foodconsumptionrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alarm',
            index=models.Index(fields=['status'], name='alarms_alar_status_f24f28_idx'),
        ),
        migrations.AddIndex(
            model_name='alarm',
            index=models.Index(fields=['alarm_type'], name='alarms_alar_alarm_t_c45f54_idx'),
        ),
        migrations.AddIndex(
            model_name='alarm',
            index=models.Index(fields=['priority'], name='alarms_alar_priorit_7d8de9_idx'),
        ),
        migrations.AddIndex(
            model_name='alarm',
            index=models.Index(fields=['status', 'priority'], name='alarms_alar_status_2e2472_idx'),
        ),
        migrations.AddIndex(
            model_name='alarm',
            index=models.Index(fields=['farm', 'status'], name='alarms_alar_farm_id_56db24_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['recipient', 'is_deleted', 'read_at'], name='alarms_noti_recipie_e8c58a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['recipient', 'created_at'], name='alarms_noti_recipie_737bf5_idx'),
        ),
    ]
