# Generated by Django 5.2.6 on 2025-12-20 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0002_shed'),
        ('flocks', '0005_alter_breedreference_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('viral', 'Viral'), ('bacterial', 'Bacteriana'), ('parasitic', 'Parasitaria'), ('fungal', 'Fúngica'), ('nutritional', 'Nutricional'), ('other', 'Otra')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], max_length=20)),
                ('transmission_mode', models.CharField(choices=[('direct', 'Directa'), ('airborne', 'Aérea'), ('water', 'Agua'), ('vector', 'Vector'), ('vertical', 'Vertical')], max_length=20)),
                ('symptoms', models.JSONField(default=list)),
                ('affected_systems', models.JSONField(default=list)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('treatments', models.JSONField(default=list)),
                ('prevention_measures', models.JSONField(default=list)),
                ('vaccine_available', models.CharField(blank=True, max_length=200, null=True)),
                ('incubation_period_days', models.IntegerField(blank=True, null=True)),
                ('mortality_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('morbidity_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_notifiable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BiosecurityChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_type', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('pre_flock', 'Pre-Lote'), ('post_flock', 'Post-Lote'), ('emergency', 'Emergencia')], max_length=20)),
                ('performed_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('completed', 'Completado'), ('incomplete', 'Incompleto'), ('failed', 'Fallido')], max_length=20)),
                ('items', models.JSONField(default=list)),
                ('compliance_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.TextField(blank=True, null=True)),
                ('photo_urls', models.JSONField(blank=True, default=list)),
                ('corrective_actions', models.TextField(blank=True, null=True)),
                ('corrective_actions_deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biosecurity_checklists', to='farms.farm')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biosecurity_checklists', to='farms.shed')),
            ],
            options={
                'ordering': ['-performed_date'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('medication_type', models.CharField(choices=[('antibiotic', 'Antibiótico'), ('antiparasitic', 'Antiparasitario'), ('vitamin', 'Vitamina'), ('probiotic', 'Probiótico'), ('vaccine', 'Vacuna'), ('other', 'Otro')], max_length=20)),
                ('active_ingredient', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('duration_days', models.IntegerField()),
                ('dosage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dosage_unit', models.CharField(max_length=20)),
                ('administration_route', models.CharField(choices=[('water', 'Agua'), ('feed', 'Alimento'), ('injection', 'Inyección'), ('oral', 'Oral')], max_length=20)),
                ('frequency', models.CharField(choices=[('once_daily', 'Una vez al día'), ('twice_daily', 'Dos veces al día'), ('three_times_daily', 'Tres veces al día'), ('continuous', 'Continuo')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('withdrawal_period_days', models.IntegerField(blank=True, null=True)),
                ('withdrawal_end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('completed', 'Completado'), ('discontinued', 'Descontinuado')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('application_dates', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='flocks.flock')),
                ('prescribed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=200)),
                ('vaccine_type', models.CharField(choices=[('viral', 'Viral'), ('bacterial', 'Bacteriana'), ('parasitic', 'Parasitaria')], max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('applied_date', models.DateTimeField(blank=True, null=True)),
                ('administration_route', models.CharField(choices=[('oral', 'Oral'), ('injection', 'Inyección'), ('spray', 'Spray'), ('water', 'Agua')], max_length=20)),
                ('dosage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dosage_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('bird_count', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('applied', 'Aplicada'), ('missed', 'Perdida'), ('rescheduled', 'Reprogramada')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='flocks.flock')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='VeterinaryVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField()),
                ('visit_type', models.CharField(choices=[('routine', 'Rutina'), ('emergency', 'Emergencia'), ('vaccination', 'Vacunación'), ('treatment', 'Tratamiento')], max_length=20)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('prescribed_medications', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('photo_urls', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('in_progress', 'En Progreso'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='scheduled', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veterinary_visits', to='flocks.flock')),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veterinary_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
    ]
