# Generated by Django 5.2.6 on 2026-02-01 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_add_veterinarians_to_farm'),
        ('flocks', '0006_add_weight_alert_fields'),
        ('veterinary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veterinaryvisit',
            name='flock',
        ),
        migrations.AddField(
            model_name='veterinaryvisit',
            name='expected_duration_days',
            field=models.PositiveIntegerField(default=1, help_text='Duración estimada en días'),
        ),
        migrations.AddField(
            model_name='veterinaryvisit',
            name='farm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veterinary_visits', to='farms.farm'),
        ),
        migrations.AddField(
            model_name='veterinaryvisit',
            name='flocks',
            field=models.ManyToManyField(blank=True, related_name='veterinary_visits', to='flocks.flock'),
        ),
        migrations.AddField(
            model_name='veterinaryvisit',
            name='reason',
            field=models.TextField(blank=True, help_text='Motivo de la visita'),
        ),
        migrations.AlterField(
            model_name='veterinaryvisit',
            name='visit_date',
            field=models.DateTimeField(help_text='Fecha y hora de inicio de la visita'),
        ),
    ]
